;; Sean's Emacs Config!

(add-to-list 'load-path "~/.emacs.d/el-get/el-get")
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.github.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(setq
 el-get-sources
 '(el-get
   wanderlust
   ac-etags
   achievements
   ac-inf-ruby
   ac-ispell
   ac-js2
   ack-and-a-half
   aes
   alert
   alpha
   android-mode
   angry-police-captain
   anything
   apache-mode
   apt-utils
   apt-utils-ido
   arduino-mode
   auto-capitalize
   auto-compile
   auto-complete
   auto-complete-c-headers
   auto-dictionary
   auto-highlight-symbol
   auto-indent-mode
   autopair
   auto-save-buffers-enhanced
   auto-shell-command
   awk-it
   back-button
   backtrace-mode
   bar-cursor
   bbdb-
   bbdb
   bbdb-ext
   bind-key
   bind-key
   bitly
   browse-url-dwim
   bundler
   butler
   button-lock
   calfw
   calfw-gcal
   capture
   cedit
   c-eldoc
   charmap
   chess
   circe
   clojure-mode
   cmake-mode
   cmake-project
   code-headers
   coffee-mode
   column-enforce-mode
   column-enforce-mode
   columnify
   confluence
   cperl-mode
   cppcheck
   crab
   creole
   crontab-mode
   csharp-mode
   css-eldoc
   csv-mode
   csv-mode
   ctable
   ctags
   ctags-update
   dart-mode
   dash
   db
   dedicated
   deferred
   diff-git
   diff-hl
   dired+
   dired-details
   dired-details+
   dired-efap
   dired-hacks-utils
   dired-isearch
   dired-rainbow
   dired-single
   dired-toggle
   dired-toggle-sudo
   disaster
   dna-mode
   docbook
   doc-mode
   dom
   dot-mode
   dropbox
   dropdown-list
   dtrt-indent
   dummy-h-mode
   easy-kill
   ecb
   editorconfig
   eimp
   eldoc-eval
   eldoc-extension
   electric-case
   elfeed
   elnode
   emms
   emms-info-mediainfo
   emms-mark-ext
   emms-soundcloud
   enh-ruby-mode
   epic
   epl
   epresent
   eproject
   erc-hl-nicks
   erc-image
   erc-tweet
   eredis
   erlang
   es-lib
   es-windows
   esxml
   evernote-mode
   f
   facebook
   fakir
   findr
   fixmee
   flymake
   flymake-checkers
   flymake-coffee
   flymake-css
   flymake-csslint
   flymake-cursor
   flymake-easy
   flymake-go
   flymake-haml
   flymake-haskell-multi
   flymake-jshint
   flymake-jslint
   flymake-json
   flymake-less
   flymake-lua
   flymake-php
   flymake-phpcs
   flymake-puppet
   flymake-ruby
   flymake-sass
   flymake-shell
   flymake-yaml
   flyspell-lazy
   fm
   fold-dwim
   fold-this
   font-lock+
   font-utils
   framemove
   free-keys
   fringe-current-line
   fringe-helper
   fullscreen-mode
   gccsense
   gdb-shell
   geben
   gh
   gist
   gitattributes-mode
   git-blame
   git-commit
   git-commit-mode
   git-commit-training-wheels-mode
   gitconfig-mode
   git-dwim
   git-gutter+
   git-gutter
   git-gutter-fringe
   github-browse-file
   gitignore-mode
   git-rebase-mode
   gnuplot
   gnuplot-mode
   go-mode
   google-contacts
   google-c-style
   google-maps
   google-this
   google-translate
   google-weather
   gplusify
   grizzl
   groovy-mode
   hackernews
   haml-mode
   ham-mode
   handlebars-mode
   haskell-mode
   helm
   heroku
   hide-lines
   highlight
   highlight-80+
   highlight-current-line
   highlight-escape-sequences
   highlight-indentation
   highlight-parentheses
   highlight-symbol
   highlight-unique-symbol
   howdoi
   htmlize
   html-to-markdown
   httpcode
   httpd
   http-post-simple
   httprepl
   idle-highlight-mode
   idle-highlight-mode
   ido-complete-space-or-hyphen
   ido-gnus
   ido-hacks
   ido-yes-or-no
   image+
   image-dired+
   imgur
   indicators
   inflections
   inf-mongo
   inf-php
   inf-ruby
   jabber
   jade-mode
   java-file-create
   javap-8
   javap-mode
   javarun
   jenkins-watch
   jira
   jquery-doc
   js2-mode
   js2-refactor
   js3-mode
   js-comint
   json-mode
   jss
   jump
   keyfreq
   know-your-http-well
   kv
   lcs
   legalese
   less-css-mode
   levenshtein
   linum-off
   linum-relative
   list-utils
   log4e
   logito
   lolcode-mode
   look-mode
   look-mode
   lorem-ipsum
   lua-mode
   lui
   magit
   magit-commit-training-wheels
   malabar-mode
   markdown-mode
   mc-extras
   minimap
   mode
   mode
   mongo
   multiple-cursors
   multi-term
   multi-web-mode
   muse
   mustache-mode
   nanowrimo
   nav-flash
   newsticker
   nginx-mode
   nodejs-repl
   noflet
   nxml-mode
   nyan-mode
   oauth2
   oauth
   octomacs
   offlineimap
   openwith
   org
   org-bullets
   org-jekyll
   org-jira
   orglue
   org-mac-link
   org-octopress
   org-present
   outline-magic
   packed
   paredit
   paredit-everywhere
   paren-face
   parenface-plus
   parse-csv
   pcache
   perl-completion
   perlcritic
   perl-myvar
   persistent-soft
   perspective
   pgdevenv
   php-auto-yasnippets
   php-boris
   php-eldoc
   php-extras
   php+-mode
   php-mode
   pkg-info
   pomodoro
   popup
   popwin
   pretty-mode
   pretty-mode
   processing-mode
   project
   project-explorer
   projectile
   projectile-rails
   project-mode
   prolog
   puppetfile-mode
   puppet-mode
   pylint
   pymacs
   python
   python-info
   python-pep8
   python-pylint
   railgun
   rainbow-delimiters
   rainbow-mode
   rase
   rbenv
   rcirc-color
   rcirc-notify
   rect+
   rect-mark
   regex-tool
   request
   requirejs-mode
   restclient
   rfringe
   rhtml-mode
   rinari
   robe
   rsense
   rspec-mode
   rtags
   ruby-additional
   ruby-block
   ruby-compilation
   ruby-dev
   ruby-electric
   ruby-end
   ruby-hash-syntax
   ruby-interpolation
   ruby-mode
   ruby-refactor
   ruby-test-mode
   ruby-tools
   s
   sass-mode
   scala-mode
   scratch
   screenshot
   scss-mode
   shell-command
   shell-here
   shorten
   show-css
   shut-up
   simple-httpd
   simplezen
   skewer-mode
   skewer-mode
   skype
   smart-compile
   smarter-compile
   smart-mode
   smartparens
   smartrep
   smart-tab
   smart-tabs-mode
   sml-mode
   sml-mode
   sos
   soundcloud
   sparkline
   ssh-config-mode
   strings
   string-utils
   stripe-buffer
   stylus-mode
   sudo-ext
   sudoku
   supergenpass
   sws-mode
   syslog-mode
   tabbar-ruler
   tabula-rasa-mode
   tdd-status-mode
   tea-time
   test-case-mode
   thesaurus
   time-ext
   timestamper
   tomatinho
   top-mode
   tracking
   tumble
   tumblesocks
   twitter
   twittering-mode
   typing
   ucs-utils
   unbound
   vagrant
   virtualenv
   volume
   w3
   w3m
   watch-buffer
   wc-mode
   wc-mode
   weather
   weather-metno
   web
   websocket
   wget
   window-jump
   window-layout
   window-number
   worklog
   workspaces
   writegood-mode
   writeroom-mode
   wtf
   xclip
   xkcd
   xlicense
   xml-gen
   xmlgen
   xml-rpc
   yagist
   yaml-mode
   yard-mode
   yas-jit
   yasnippet
   yaxception
   zencoding-mode
   zen-mode
   zlc))

(el-get 'sync)

;; Let's save all the changes we make to "custom.el", 
;;  instead of this file
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file)

;; store passwords and whatnot outside the emacs folder
(load-file "~/.secure-emacs")

;; ;; load up some miscleanious settings
(load-file "~/.emacs.d/misc.el" )

;; ;; Add some load paths
(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/modes")
(add-to-list 'load-path "~/.emacs.d/downloads")

(require 'functions)
(require 'keybindings)

(require 'load-customizations)
