(require 'nginx-mode)
(require 'apache-mode)
(require 'ssh-config-mode)
(require 'gitconfig-mode)
(require 'crontab-mode)
;(require 'csv-mode)
(require 'gitattributes-mode)
(require 'pretty-mode)
(require 'ssh-config-mode)
;(require 'tabula-rasa-mode)
(require 'test-case-mode)
(require 'yaml-mode)

(require 'haml-mode)
(require 'jade-mode)
(require 'handlebars-mode)
(require 'fullscreen-mode)
(require 'rainbow-mode)

(require 'dropbox)
(require 'editorconfig)
(require 'hackernews)
(require 'heroku)
(require 'imgur)
(require 'jenkins-watch)
(require 'twitter)
(require 'tumble)
(require 'tumblesocks)
;(require 'weather)
;(require 'weather-metno)
(require 'wtf)
(require 'xlicense)
(require 'xmlgen)
(require 'yagist)
(require 'apt-utils)
(require 'apt-utils-ido)


(require 'keyfreq)
(require 'free-keys)
(require 'inflections)
(require 'legalese)
(require 'know-your-http-well)
(require 'lorem-ipsum)
(require 'mode-icons)
(require 'newsticker)
(require 'rainbow-delimiters)
(require 'screenshot)
(require 'thesaurus)
(require 'timestamper)
(require 'time-ext)

(global-pretty-mode 1)
(keyfreq-mode 1)
(keyfreq-autosave-mode 1)

(provide 'config-modes)
