(require 'yagist)
(require 'git-gutter)
(require 'git-blame)
(require 'gh)
(require 'git-commit-mode)
(require 'gitconfig-mode)
(require 'git-dwim)
(require 'git-gutter+)
(require 'git-gutter-fringe)
(require 'github-browse-file)
(require 'gitignore-mode)
(require 'git-rebase-mode)
(global-git-gutter-mode t)

(provide 'git-customize)
