(require 'highlight)
(require 'highlight-80+)
(require 'highlight-current-line)
(require 'highlight-escape-sequences)
(require 'highlight-indentation)
(require 'highlight-parentheses)
(require 'highlight-symbol)
(require 'highlight-unique-symbol)

(provide 'highlight-customize)
