(message "Loading json customizations")
(add-to-list 'auto-mode-alist '("\\.json$" . setup-json-mode))

(defun setup-json-mode () 
  (interactive)
  (require 'json-mode)
  (clean-json-mode))

(defun clean-json-mode ()
	(interactive)
  (json-mode)
	(setq tab-width 2)
	(setq c-basic-offset 2)
	(setq indent-tabs-mode t)
	(setq fill-column 78)
	(c-set-offset 'arglist-close 'c-lineup-arglist-operators)
	(c-set-offset 'arglist-intro '+)
	(c-set-offset 'arglist-cont-nonempty 'c-lineup-math)
	(c-set-offset 'topmost-intro-cont 'c-lineup-cascaded-calls)
	(c-set-offset 'brace-list-entry 'c-lineup-cascaded-calls))

(provide 'json-customize)
