(add-hook 'c-mode-common-hook   'hs-minor-mode)
(add-hook 'cc-mode-common-hook  'hs-minor-mode)
(add-hook 'c++-mode-common      'hs-minor-mode)
(add-hook 'emacs-lisp-mode-hook 'hs-minor-mode)
(add-hook 'java-mode-hook       'hs-minor-mode)
(add-hook 'lisp-mode-hook       'hs-minor-mode)
(add-hook 'perl-mode-hook       'hs-minor-mode)
(add-hook 'sh-mode-hook         'hs-minor-mode)
(add-hook 'ruby-mode-hook       'hs-minor-mode)
(add-hook 'php-mode-hook        'hs-minor-mode)

(require 'atlasian-customize)
(require 'auto-complete-customize)
(require 'c-customize)
(require 'circe-customize)
(require 'coffee-customize)
(require 'config-modes)
(require 'css-customize)
(require 'database-customize)
(require 'dired-customize)
(require 'emms-customize)
(require 'erlang-customize)
(require 'eshell-customize)
(require 'evernote-customize)
(require 'flymake-customize)
(require 'fold-customize)
(require 'git-customize)
(require 'google-customize)
(require 'highlight-customize)
(require 'html-customize)
(require 'ido-customize)
(require 'jabber-customize)
(require 'jade-customize)
(require 'javascript-customize)
(require 'json-customize)
(require 'linenum-customize)
(require 'lisp-customize)
(require 'magit-customize)
(require 'markdown-customize)
(require 'org-customize)
;;(require 'org-remember-customize)
(require 'php-customize)
(require 'puppet-customize)
(require 'ruby-customize)
(require 'term-customize)
(require 'uniquify-setup)
(require 'yasnippet-setup)
(require 'twitter-customize)
(require 'tumblr-customize)
(require 'browser-customize)
(require 'email-customize)
(require 'elget-customize)
(require 'blog-customize)
(require 'crontab-customize)
(require 'hideshow-customize)
(require 'haml-customize)

(provide 'load-customizations)
